### ISSUE TITLE
Nuevo miembro del equipo en Tarjeta 3

### ISSUE THREAD

**Issue by juanpy01** [emanuelAlavar/devtech-podcast-web#1]
Hola Emanuel, voy a colaborar con tu proyecto y agregarme como miembro del equipo del podcast DevTech. Voy a utilizar la tarjeta 3. Saludos!

**Comment by emanuelAlavar** [comment]
Perfecto Juan, espero tu aporte

**Comment by emanuelAlavar** [comment]
Buenisimo
